version: "{build}"

environment:
  RUBY_VERSION: "22-x64"   # https://www.appveyor.com/docs/installed-software#ruby

branches:
  only:
    - master
    - /^[\d.]+$/

# Uncomment to debug via RDP
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install
  - ps: (Get-Content vendor\bundle\ruby\2.2.0\gems\specinfra-2.66.6\lib\specinfra\backend\cmd.rb) | Foreach-Object {$_ -replace '-encodedCommand', '-NoProfile -encodedCommand'} | Out-File -Encoding ascii vendor\bundle\ruby\2.2.0\gems\specinfra-2.66.6\lib\specinfra\backend\cmd.rb

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec --color --format documentation spec/*_spec.rb
